-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--##############

--## MONITORS ###

--###############

hl.monitor({
	output = "DP-1",
	mode = "2560x1440@165",
	position = "6000x0",
	scale = 1,
	transform = 0,
})

hl.monitor({
	output = "DP-2",
	mode = "2560x1440@180",
	position = "0x0",
	scale = 1,
	transform = 0,
})

hl.monitor({
	output = "DP-3",
	mode = "3440x1440@144",
	position = "2560x0",
	scale = 1,
	transform = 0,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "3840x2160@60",
	position = "2560x2160",
	scale = 1,
	transform = 0,
	disabled = true,
})

--##################

--## MY PROGRAMS ###

--##################

-- Set programs that you use

local terminal = "kitty"

local fileManager = "nautilus"

local menu = "rofi -show drun"

local gnomeSchema = "org.gnome.desktop.interface"

--################

--## AUTOSTART ###

--################

-- 1288514554 Red dress tree girl

-- 1682963130 Suburb Girl

-- 2249576063 Snowy Girl

-- 2872601786 Rainy Beach

-- 3251872199 Samurai Forest

-- for GTK4 apps

--############################

--## ENVIRONMENT VARIABLES ###

--############################

hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-dark-cursors")

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("XCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "catppuccin-mocha-dark-cursors")

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("NVD_BACKEND", "direct")

hl.env("MOZ_DISABLE_RDD_SANDBOX", 1)

hl.env("TERM", "kitty")

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- env = SDL_JOYSTICK_HIDAPI_GAMECUBE,0

hl.env("GTK_IM_MODULE", "'ibus'")

hl.env("QT_IM_MODULE", "'ibus'")

hl.env("GLFW_IM_MODULE", "'ibus'")

hl.env("XMODIFIERS", "'@im=ibus'")

--####################

--## LOOK AND FEEL ###

--####################

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 6,
		border_size = 2,
		resize_on_border = true,
		extend_border_grab_area = 25,
		allow_tearing = true,
		layout = "dwindle",
		col = {
			active_border = { colors = { "rgb(cba6f7)", "rgb(f5c2e7)" }, angle = 45 },
			inactive_border = "rgb(313244)",
		},
	},
})

hl.config({
	decoration = {
		rounding = 7,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		blur = {
			enabled = false,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},
})

hl.config({
	animations = {
		enabled = true,
	},
})

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
	},
})

hl.config({
	master = {
		new_status = "master",
	},
})

hl.config({
	cursor = {
		hide_on_key_press = true,
		default_monitor = "DP-3",
	},
})

hl.config({
	misc = {
		focus_on_activate = false,
		force_default_wallpaper = -1,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		enable_swallow = true,
		swallow_regex = "^(kitty)$",
		vrr = 2,
		initial_workspace_tracking = 1,
	},
})

hl.config({
	render = {
		direct_scanout = 0,
		new_render_scheduling = true,
	},
})

--############

--## INPUT ###

--############

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "altgr-intl",
		follow_mouse = 1,
		force_no_accel = true,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		repeat_delay = 250,
		touchpad = {
			natural_scroll = false,
		},
	},
})

hl.config({
	debug = {
		disable_logs = false,
	},
})

--###################

--## KEYBINDINGSS ###

--###################

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pin())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.exec_cmd("kitty --class clipse -e clipse"))

-- My own applications

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("killall gjs && hyprpanel"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("/home/mara/scripts/wallpaper_toggle.sh"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

-- Screenshot a monitor

-- bind = $mainMod CTRL, S, exec, grimblast --cursor --freeze save output - | swappy -f -

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m window --raw --freeze| gradia"))

-- Screenshot a region

-- bind = $mainMod SHIFT, S, exec, grimblast --cursor --freeze save area - | swappy -f -

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region -z --raw --freeze| gradia"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }, { follow = false }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "X", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.workspace.toggle_special("tmp"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Z", hl.dsp.window.move({ workspace = "special:tmp" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.workspace.move({ monitor = "l" }))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.workspace.move({ monitor = "r" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- bindl=, XF86AudioRaiseVolume, exec, hyprpanel vol +3

-- bindel=, XF86AudioLowerVolume, exec, hyprpanel vol -3

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wayle audio output-volume -2"), { locked = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wayle audio output-volume +2"), { locked = true })

-- bindel=, XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

-- Requires playerctl

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

hl.window_rule({
	match = {
		title = "^(FINAL FANTASY XIV)$",
	},
	immediate = true,
})

-- floats

hl.window_rule({
	float = true,
	match = {
		class = "steam",
	},
})

hl.window_rule({
	float = true,
	match = {
		title = "Steam- News",
	},
})

hl.window_rule({
	float = true,
	match = {
		title = "^(nwg-look)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		title = "^(FF Logs Uploader)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		title = "^(Docker Desktop)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(org.speedcrunch.speedcrunch)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(org.kde.polkit-kde-authentication-agent-1)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(Bitwarden)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		title = "^(Lan Mouse)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(firefox)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(org.mozilla.Thunderbird)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(org.gnome.clocks)$",
	},
})

hl.window_rule({
	name = "size_500_500",
	match = {
		class = "^(org.gnome.clocks)$",
	},
	size = "500 500",
})

hl.window_rule({
	float = true,
	match = {
		class = "(clipse)",
	},
})

hl.window_rule({
	name = "size_622_652",
	match = {
		class = "(clipse)",
	},
	size = "622 652",
})

-- windowrule = stayfocused on,  match:class (clipse)

-- windowrulev2 = unset, title:^(FF Logs)$

hl.window_rule({
	float = true,
	match = {
		title = "^(FF Logs)$",
	},
	-- TODO: review rule: "float on"
})

hl.window_rule({
	name = "size_400_300",
	match = {
		title = "^(FF Logs)$",
	},
	size = "400 300",
})

hl.window_rule({
	name = "workspace_4",
	match = {
		title = "^(FF Logs)$",
	},
	workspace = 4,
})

-- windowrulev2 = pin, title:^(FF Logs)$

hl.window_rule({
	name = "size_1300_800",
	match = {
		class = "^(org.pulseaudio.pavucontrol)$",
	},
	size = "1300 800",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "^(org.pulseaudio.pavucontrol)$",
	},
	center = true,
})

hl.window_rule({
	float = true,
	match = {
		class = "^(org.pulseaudio.pavucontrol)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(be.alexandervanhee.gradia)$",
	},
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "^(be.alexandervanhee.gradia)$",
	},
	center = true,
})

hl.window_rule({
	float = true,
	match = {
		class = "^(Slippi Launcher)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(Apprun)$",
	},
})

hl.window_rule({
	name = "tile_on",
	match = {
		title = "^(Dolphin)$",
	},
	tile = true,
})

hl.window_rule({
	float = true,
	match = {
		class = "^(org.gnome.Nautilus)$",
	},
})

hl.window_rule({
	name = "size_1500_1000",
	match = {
		class = "^(org.gnome.Nautilus)$",
	},
	size = "1500 1000",
})

hl.window_rule({
	float = true,
	match = {
		class = "^(rwing)$",
	},
})

hl.window_rule({
	float = true,
	match = {
		class = "^(Bitwarden)$",
	},
})

hl.window_rule({
	name = "size_1500_1000",
	match = {
		class = "^(Bitwarden)$",
	},
	size = "1500 1000",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "^(Bitwarden)$",
	},
	center = true,
})

hl.window_rule({
	name = "center_on",
	match = {
		title = "^(Open Files)$",
	},
	center = true,
})

hl.window_rule({
	name = "size_500_800",
	match = {
		title = "^(Friends List)$",
	},
	size = "500 800",
})

hl.window_rule({
	name = "size_1600_900",
	match = {
		title = "^(Steam)$",
	},
	size = "1600 900",
})

hl.window_rule({
	name = "center_on",
	match = {
		title = "^(Steam)$",
	},
	center = true,
})

hl.window_rule({
	name = "size_1600_900",
	match = {
		class = "^(Docker Desktop)$",
	},
	size = "1600 900",
})

hl.window_rule({
	name = "center_on",
	match = {
		class = "^(Docker Desktop)$",
	},
	center = true,
})

-- default workspaces

hl.window_rule({
	name = "workspace_1_silent",
	match = {
		class = "^(firefox)$",
	},
	workspace = "1 silent",
})

hl.window_rule({
	name = "workspace_3_silent",
	match = {
		class = "^(discord)$",
	},
	workspace = "3 silent",
})

hl.window_rule({
	name = "workspace_3_silent",
	match = {
		class = "^(vesktop)$",
	},
	workspace = "3 silent",
})

hl.window_rule({
	name = "workspace_4_silent",
	match = {
		class = "^(steam)$",
	},
	workspace = "4 silent",
})

hl.window_rule({
	name = "workspace_4_silent",
	match = {
		class = "^(XIVLauncher.Core)$",
	},
	workspace = "4 silent",
})

hl.window_rule({
	name = "workspace_4",
	match = {
		class = "^(steam_app_39210)$",
	},
	workspace = 4,
})

hl.window_rule({
	name = "workspace_4",
	match = {
		class = "^(ffxiv_dx11.exe)$",
	},
	workspace = 4,
})

hl.window_rule({
	name = "workspace_5_silent",
	match = {
		class = "^(Spotify)$",
	},
	workspace = "5 silent",
})

hl.window_rule({
	name = "workspace_6_silent",
	match = {
		class = "^(org.mozilla.Thunderbird)$",
	},
	workspace = "6 silent",
})

hl.window_rule({
	name = "workspace_2_silent",
	match = {
		class = "^(Godot)$",
	},
	workspace = "2 silent",
})

hl.window_rule({
	name = "workspace_4_silent",
	match = {
		class = "^(REAPER)$",
	},
	workspace = "4 silent",
})

-- windowrule = move cursor, match:class REAPER, match:float 1

hl.window_rule({
	name = "no_initial_focus_on",
	match = {
		class = "REAPER",
		title = "^(menu)$",
	},
	-- TODO: review rule: "no_initial_focus on"
})

hl.window_rule({
	name = "no_initial_focus_on",
	match = {
		class = "REAPER",
		title = "^$",
	},
	-- TODO: review rule: "no_initial_focus on"
})

-- fixes for xwaylandvideobridge

-- windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$

-- windowrule = noanim on, match:class ^(xwaylandvideobridge)$

-- windowrule = noinitialfocus on, match:class ^(xwaylandvideobridge)$

-- windowrule = maxsize 1 1, match:class ^(xwaylandvideobridge)$

-- windowrule = noblur, match:class ^(xwaylandvideobridge)$

-- workspace rules

hl.workspace_rule({
	workspace = 1,
	monitor = "DP-2",
})

hl.workspace_rule({
	workspace = 2,
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = 3,
	monitor = "DP-1",
})

hl.workspace_rule({
	workspace = 4,
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = 5,
	monitor = "DP-3",
})

hl.workspace_rule({
	workspace = 6,
	monitor = "DP-3",
})

-- workspace = 4, gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:4

-- windowrule = rounding 0, floating:0, onworkspace:4

-- PoE Overlay

-- windowrulev2 = tag +apt, title:(Exiled Exchange 2)

-- windowrulev2 = float, tag:apt

-- windowrulev2 = nofocus, tag:apt

-- windowrulev2 = noborder, tag:apt

-- windowrulev2 = pin, tag:apt

-- windowrulev2 = size 100% 100%, tag:apt

-- windowrulev2 = float,initialclass:^(steam_app_2694490)$

hl.window_rule({
	name = "fullscreen_on",
	match = {
		class = "^(steam_app_2694490)$",
	},
	fullscreen = true,
})

-- windowrulev2 = stayfocused,initialclass:^(steam_app_2694490)$

-- windowrulev2 = nofocus,fullscreen,class:net-runelite-client-RuneLite,title:^(win\d+)$

hl.window_rule({
	name = "no_initial_focus_on",
	match = {
		class = "^(Ibus-ui-gtk3)$",
	},
	-- TODO: review rule: "no_initial_focus on"
})

-- windowrulev2 = tag +apt, title:(Awakened PoE Trade)

-- windowrulev2 = float, tag:apt

-- windowrulev2 = noblur, tag:apt

-- windowrulev2 = nofocus, tag:apt # Disable auto-focus

-- windowrulev2 = noshadow, tag:apt

-- windowrulev2 = noborder, tag:apt

-- windowrulev2 = pin, tag:apt

-- windowrulev2 = renderunfocused, tag:apt

-- windowrulev2 = size 100% 100%, tag:apt

-- windowrulev2 = center, tag:apt

--

--

-- windowrulev2 = tag +poe, title:(Path of Exile)

-- windowrulev2 = tag +poe, class:(steam_app_238960)

-- windowrulev2 = fullscreen, tag:poe

-- windowrulev2 = noborder, tag:poe

-- windowrulev2 = norounding, tag:poe

-- windowrulev2 = size 100% 100%, tag:poe

-- bind = SHIFT,Space,pass,^(awakened-poe-trade)$

-- bind = CTRL,D,pass,^(awakened-poe-trade)$

-- bind = CTRL ALT,D,pass,^(awakened-poe-trade)$

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user import-environment HYPRLAND_INSTANCE_SIGNATURE")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("wayle panel start")
	hl.exec_cmd("clipse -listen")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd(
		"sleep 3; linux-wallpaperengine --no-audio-processing --silent --screen-root DP-3 --fps 30 3251872199 --screenshot "
			.. os.getenv("HOME")
			.. "/.config/background.png"
	)
	hl.exec_cmd("sleep 1; magick convert ~/.config/background.png -flip ~/.config/background_flipped.png")
	hl.exec_cmd("[workspace 2] kitty")
	hl.exec_cmd('/home/mara/scripts/hyprland.sh "firefox" "org.mozilla.Thunderbird"')
	hl.exec_cmd("xrandr --output DP-3 --primary")
	hl.exec_cmd("[workspace 1 silent; tile] firefox")
	hl.exec_cmd("sleep 2; vesktop & spotify")
	hl.exec_cmd("sleep 2; thunderbird & steam & bitwarden-desktop")
	hl.exec_cmd("sleep 3; wpaperd")
	hl.exec_cmd("sleep 2; ibus start --type wayland")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
	hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Breeze-Dark'")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'breeze-dark'")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'catppuccin-mocha-dark-cursors'")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'Open Sans 10'")
	hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
end)
