# example configuration

# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

# optional port (defaults to 4242)
port = 4242
# # optional frontend -> defaults to gtk if available
# # possible values are "cli" and "gtk" 
# frontend = "gtk"

# define a client on the left side with IP address 192.168.178.189
[bottom]
# The hostname is optional: When no hostname is specified,
# at least one ip address needs to be specified.
hostname = "Josh-Notebook"
# optional port
port = 4242
